export const RoleDataList: string[] = [
    
    'Dashboard',
    'Bulletins employé',
    'Personnels',
    'Pointages', 
    'Registre de presences', 
    'Heure suplementaires',
    'Liste de paiements', 
    'Statuts de paies',
    'Relevés de paies',
    'Avances salaires',
    'Primes divers',
    'Pénalites',
    'Pret entreprise', 
    'Syndicats', 
    'Horaires', 
    'Performences', 
    'Postes',
    'Candidatures',
    'Emails',
    'Preferences',
    'Reglages',
    'Departements',
    'Sites location',
    'Fonctions', 
    'Services',
    'Titres',
    'Archives',
  ]

  export const RoleSupportDataList: string[] = [
    'Dashboard',
    'Bulletins employé',
    'Personnels', 
    'Pointages', 
    'Registre de presences', 
    'Heure suplementaires',
    'Liste de paiements', 
    'Statuts de paies',
    'Relevés de paies',
    'Avances salaires',
    'Primes divers',
    'Pénalites',
    'Pret entreprise', 
    'Syndicats', 
    'Horaires', 
    'Performences', 
    'Postes',
    'Candidatures',
    'Emails',
    'Preferences',
    'Reglages',
    'Departements',
    'Sites location',
    'Fonctions', 
    'Services',
    'Titres',
    'Archives',
    'Support',
  ]